"""Added user id column to conversion history table

Revision ID: 7d82c404dec0
Revises: 98f5726393b4
Create Date: 2022-07-20 19:29:13.440580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d82c404dec0'
down_revision = '98f5726393b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversionhistory', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversionhistory', 'user_id')
    # ### end Alembic commands ###
