"""Modified user id column to be a relationship

Revision ID: a0ba1f88216c
Revises: 7d82c404dec0
Create Date: 2022-07-20 19:32:07.145591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ba1f88216c'
down_revision = '7d82c404dec0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversionhistory', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversionhistory', type_='foreignkey')
    # ### end Alembic commands ###
