"""Modified currency string limit to accomodate longer symbols

Revision ID: f7526ffc5d7d
Revises: a0ba1f88216c
Create Date: 2022-07-20 21:12:46.651896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7526ffc5d7d'
down_revision = 'a0ba1f88216c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
